## Exercise 2 - Implementing the LU Decomposition

Your exercise today is straight forward. Write a function `lu(A)`, which takes a matrix $A$ and returns the factors $L$ and $U$ of the LU decomposition.

* Try to vectorize the code, that means the inner-most operation of subtracting a multiple of one row from another row should be performed by operating on the whole slice of the corresponding matrix. Overall, your code should only require a double-for loop.
* Test your function by computing $\|A-LU\|$. If this value is in the order of machine precision for various examples your algorithm should be correct.
* Compare the speed of your LU decomposition with the speed of the `scipy.linalg.lu` function.
* You may want to use the following skeleton to write your LU function.

In [1]:
def lu(A):
    
    import numpy as np
    
    # Return an error if matrix is not square
    if not A.shape[0]==A.shape[1]:
        raise ValueError("Input matrix must be square")
        
    n = A.shape[0] # The number of rows/columns of A
    
    L = np.zeros((n,n),dtype='float64') # Reserve space for L
    U = np.zeros((n,n),dtype='float64') # Reserve space for U
    U[:] = A # Copy A into U as we do not want to modify A
    np.fill_diagonal(L,1) # fill the diagonal of L with 1
    
    for i in range(n-1):
        # The outer iteration 
        for j in range(i+1,n):
            # Now subtract from the j-th row a multiple of the i-th row.
            # Store the scalars in the L matrix
            pass # Delete this line when you fill in code
    return (L,U)

In [2]:
# Test implementation
import numpy as np

n = 5
A = np.random.rand(n,n)
L,U = lu(A)
residual = np.linalg.norm(A-np.dot(L,U))
print("The residual is {0}".format(residual))

# Show L and U
print(L)
print(U)

The residual is 0.0
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.21354434 0.19984934 0.91730991 0.47611133 0.27561457]
 [0.86595502 0.99712793 0.77275063 0.10688847 0.03707039]
 [0.42599253 0.54883323 0.21948703 0.35717532 0.38415195]
 [0.99921086 0.18211658 0.23005131 0.41173091 0.46526805]
 [0.29306929 0.90502971 0.48314928 0.55131447 0.98723261]]
